//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace feri.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class daiEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new daiEntities object using the connection string found in the 'daiEntities' section of the application configuration file.
        /// </summary>
        public daiEntities() : base("name=daiEntities", "daiEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new daiEntities object.
        /// </summary>
        public daiEntities(string connectionString) : base(connectionString, "daiEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new daiEntities object.
        /// </summary>
        public daiEntities(EntityConnection connection) : base(connection, "daiEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<student> students
        {
            get
            {
                if ((_students == null))
                {
                    _students = base.CreateObjectSet<student>("students");
                }
                return _students;
            }
        }
        private ObjectSet<student> _students;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<employee> employees
        {
            get
            {
                if ((_employees == null))
                {
                    _employees = base.CreateObjectSet<employee>("employees");
                }
                return _employees;
            }
        }
        private ObjectSet<employee> _employees;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<employee_salary_Details> employee_salary_Details
        {
            get
            {
                if ((_employee_salary_Details == null))
                {
                    _employee_salary_Details = base.CreateObjectSet<employee_salary_Details>("employee_salary_Details");
                }
                return _employee_salary_Details;
            }
        }
        private ObjectSet<employee_salary_Details> _employee_salary_Details;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the students EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTostudents(student student)
        {
            base.AddObject("students", student);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the employees EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToemployees(employee employee)
        {
            base.AddObject("employees", employee);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the employee_salary_Details EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToemployee_salary_Details(employee_salary_Details employee_salary_Details)
        {
            base.AddObject("employee_salary_Details", employee_salary_Details);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="daiModel", Name="employee")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class employee : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new employee object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static employee Createemployee(global::System.Int32 id)
        {
            employee employee = new employee();
            employee.id = id;
            return employee;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String address
        {
            get
            {
                return _address;
            }
            set
            {
                OnaddressChanging(value);
                ReportPropertyChanging("address");
                _address = StructuralObject.SetValidValue(value, true, "address");
                ReportPropertyChanged("address");
                OnaddressChanged();
            }
        }
        private global::System.String _address;
        partial void OnaddressChanging(global::System.String value);
        partial void OnaddressChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="daiModel", Name="employee_salary_Details")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class employee_salary_Details : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new employee_salary_Details object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static employee_salary_Details Createemployee_salary_Details(global::System.Int32 id)
        {
            employee_salary_Details employee_salary_Details = new employee_salary_Details();
            employee_salary_Details.id = id;
            return employee_salary_Details;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> employee_id
        {
            get
            {
                return _employee_id;
            }
            set
            {
                Onemployee_idChanging(value);
                ReportPropertyChanging("employee_id");
                _employee_id = StructuralObject.SetValidValue(value, "employee_id");
                ReportPropertyChanged("employee_id");
                Onemployee_idChanged();
            }
        }
        private Nullable<global::System.Int32> _employee_id;
        partial void Onemployee_idChanging(Nullable<global::System.Int32> value);
        partial void Onemployee_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> salary_paid
        {
            get
            {
                return _salary_paid;
            }
            set
            {
                Onsalary_paidChanging(value);
                ReportPropertyChanging("salary_paid");
                _salary_paid = StructuralObject.SetValidValue(value, "salary_paid");
                ReportPropertyChanged("salary_paid");
                Onsalary_paidChanged();
            }
        }
        private Nullable<global::System.Decimal> _salary_paid;
        partial void Onsalary_paidChanging(Nullable<global::System.Decimal> value);
        partial void Onsalary_paidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> paid_date
        {
            get
            {
                return _paid_date;
            }
            set
            {
                Onpaid_dateChanging(value);
                ReportPropertyChanging("paid_date");
                _paid_date = StructuralObject.SetValidValue(value, "paid_date");
                ReportPropertyChanged("paid_date");
                Onpaid_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _paid_date;
        partial void Onpaid_dateChanging(Nullable<global::System.DateTime> value);
        partial void Onpaid_dateChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="daiModel", Name="student")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class student : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new student object.
        /// </summary>
        /// <param name="sid">Initial value of the sid property.</param>
        public static student Createstudent(global::System.Int32 sid)
        {
            student student = new student();
            student.sid = sid;
            return student;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 sid
        {
            get
            {
                return _sid;
            }
            set
            {
                if (_sid != value)
                {
                    OnsidChanging(value);
                    ReportPropertyChanging("sid");
                    _sid = StructuralObject.SetValidValue(value, "sid");
                    ReportPropertyChanged("sid");
                    OnsidChanged();
                }
            }
        }
        private global::System.Int32 _sid;
        partial void OnsidChanging(global::System.Int32 value);
        partial void OnsidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sname
        {
            get
            {
                return _sname;
            }
            set
            {
                OnsnameChanging(value);
                ReportPropertyChanging("sname");
                _sname = StructuralObject.SetValidValue(value, true, "sname");
                ReportPropertyChanged("sname");
                OnsnameChanged();
            }
        }
        private global::System.String _sname;
        partial void OnsnameChanging(global::System.String value);
        partial void OnsnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String saddress
        {
            get
            {
                return _saddress;
            }
            set
            {
                OnsaddressChanging(value);
                ReportPropertyChanging("saddress");
                _saddress = StructuralObject.SetValidValue(value, true, "saddress");
                ReportPropertyChanged("saddress");
                OnsaddressChanged();
            }
        }
        private global::System.String _saddress;
        partial void OnsaddressChanging(global::System.String value);
        partial void OnsaddressChanged();

        #endregion

    }

    #endregion

}
